version: "3"
services:
  web:
    image: sofiegraham/content-microservice
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "80:8080"
    networks:
      - webnet
networks:
  webnet: